from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import BigInteger, DateTime, ForeignKey, Numeric, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base


class BatchCompressedText(Base):
    """Stores the S3 storage UUID for a compressed text result per batch challenge.

    One row per BatchChallenge (i.e. per unique challenge + compression_ratio pair
    within a given challenge batch). The ``storage_uuid`` is generated by mcp_platform
    before dispatching to the sandbox service and is used as the S3 object key:
    ``compressed-texts/{storage_uuid}``.
    """

    __tablename__ = "batch_compressed_texts"
    __table_args__ = (
        UniqueConstraint(
            "batch_challenge_fk",
            name="uq_batch_compressed_texts_batch_challenge",
        ),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    batch_challenge_fk: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("batch_challenges.id", ondelete="CASCADE"),
        nullable=False,
    )
    storage_uuid: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        unique=True,
    )
    execution_time_seconds: Mapped[float | None] = mapped_column(
        Numeric(10, 4),
        nullable=True,
        comment="Time in seconds taken to compress this text in the sandbox",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
