"""
API contracts for sandbox service.
"""
from __future__ import annotations

from typing import Any, List, Optional
from pydantic import BaseModel, Field


class ExecuteBatchRequest(BaseModel):
    """Request to execute a batch of compression tasks."""

    batch_id: str = Field(..., description="Unique identifier for this batch (used for logging)")
    script_presigned_url: str = Field(
        ...,
        description=(
            "Presigned S3 URL (GET) for temporary read access to the miner's challenge script. "
            "The sandbox uses this URL to download the script without direct S3 credentials."
        ),
    )
    challenge_texts: List[str] = Field(..., description="Texts to compress")
    compression_ratios: List[Optional[float]] = Field(
        ..., description="Target compression ratios"
    )
    storage_presigned_urls: List[str] = Field(
        ...,
        description=(
            "Presigned S3 URLs (PUT), one per challenge_text entry. "
            "The sandbox uploads each compressed result to the designated URL "
            "without requiring direct S3 credentials."
        ),
    )
    timeout_per_task: float = Field(..., description="Timeout for each individual task in seconds")
    container_timeout: float = Field(..., description="Global timeout for entire container execution in seconds")


class ExecuteBatchResponse(BaseModel):
    """Response from batch execution."""
    
    success: bool = Field(..., description="Whether execution succeeded")
    batch_id: str = Field(..., description="Batch identifier")
    error: Optional[str] = Field(default=None, description="Error message if entire batch failed")
    task_errors: List[Optional[str]] = Field(
        default_factory=list,
        description="Per-task error messages, one entry per challenge_text. None if the task succeeded, error string if it failed.",
    )
    execution_times: List[Optional[float]] = Field(
        default_factory=list,
        description="Per-task execution times in seconds, one entry per challenge_text. None if the task failed or time is unavailable.",
    )


class CompactBenchRunTaskRequest(BaseModel):
    """Single benchmark execution request for the compact-bench backend."""

    benchmark: str = Field(..., description="Benchmark dataset identifier.")
    instance_id: str = Field(..., description="Concrete benchmark instance identifier.")
    run_id: int = Field(..., description="Run identifier for this execution.")
    storage_presigned_url: str = Field(
        ...,
        description=(
            "Presigned S3 URL (PUT) used to upload the captured agent patch for this task. "
            "The service may skip uploading when the patch is empty."
        ),
    )
    agent_name: str = Field(default="openclaw", description="Compact-bench runtime backend name.")
    model: str | None = Field(default=None, description="Optional LLM model override.")
    openclaw_timeout: int | None = Field(default=1800, description="Optional timeout override for OpenClaw execution in seconds.")
    openclaw_disable_somarizer: bool = Field(default=False)
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Opaque task metadata echoed back in the response for caller correlation.",
    )


class CompactBenchRunTaskResponse(BaseModel):
    """Per-task execution result for the compact-bench backend."""
    success: bool = Field(..., description="Whether request was accepted successfully for execution.")


class CompactBenchReportRequest(BaseModel):
    """Per-task execution result for the compact-bench backend."""

    run_id: int = Field(..., description="Run identifier for this execution.")
    ok_status: bool = Field(..., description="Compact-bench/OpenClaw runtime status.")
    error: str | None = Field(default=None, description="Task-level error message.")
    execution_time_seconds: float | None = Field(
        default=None,
        description="Observed end-to-end runtime for the benchmark solve command.",
    )
    total_tokens: int | None = Field(
        default=None,
        description="Total token count reported by the benchmark runtime for this run.",
    )
    agent_steps: int | None = Field(
        default=None,
        description="Best-effort count of agent steps observed during execution.",
    )
    patch_capture_status: bool = Field(..., description="Whether the patch capture was successful and uploaded to S3.")
    patch_diff: str | None = Field(
        default=None,
        description=(
            "Unified diff string representing the changes made by the agent, generated by compact-bench/OpenClaw's patch capture. "
            "This may be None if the patch capture failed or if no changes were made."
        ),
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Opaque execution metadata for debugging and downstream processing.",
    )

class CompactBenchReportResponse(BaseModel):
    """Per-task execution result for the compact-bench backend."""
    success: bool = Field(..., description="Whether request was accepted successfully for execution.")

class ApiGatewayProxyPayload(BaseModel):
    method: str = Field(default="POST", description="HTTP method for upstream request.")
    url: str = Field(..., description="Upstream URL to proxy to.")
    headers: dict[str, str] = Field(default_factory=dict, description="Upstream request headers.")
    timeout_seconds: float = Field(default=30.0, description="Per-request timeout for upstream call.")
    body: dict[str, Any] | list[Any] | str | None = Field(
        default=None,
        description="Inline request payload.",
    )


class ApiGatewayRequest(BaseModel):
    """Generic API Gateway request wrapper."""
    body: ApiGatewayProxyPayload = Field(..., description="Typed proxy request payload.")
    run_id: int = Field(..., description="Run identifier for this execution, used for logging and correlation.")
    
class ApiGatewayResponse(BaseModel):
    """Generic API Gateway response wrapper."""
    success: bool = Field(..., description="Whether the request was processed successfully.")
    error: Optional[str] = Field(default=None, description="Error message if processing failed.")
    status_code: int | None = Field(default=None, description="Upstream HTTP status code when available.")
    headers: dict[str, str] | None = Field(default=None, description="Selected upstream response headers.")
    body: str | None = Field(default=None, description="Raw response payload from upstream, if applicable.")
